### ISSUE TITLE
vagrant-cachier

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/macbook-pro-battery-test#7]
Did you run the tests with `vagrant-cachier` installed or no? If you did, it might need to be clarified as well.

**Comment by geerlingguy** [comment]
Hmm... I'm going to check.

**Comment by geerlingguy** [comment]
It looks like it _wasn't_ installed on the two 2016 models, but it _was_ installed on my 2015 Pro. That could skew the test a <s>little</s> lot, as the 2015 model wouldn't have had to re-download all the apt packages (and composer too, right?) on each run.

That would also explain the huge delta in the average test speed!

I'll have to re-run the test with `cachier` uninstalled on my 2015 Pro tonight.

**Comment by geerlingguy** [comment]
In any case, the 2016 model comparison is still valid, I just need to see if I get largely different results from the 2015. Good catch!

**Comment by geerlingguy** [comment]
@oxyc - Thanks again for pointing this out! I ran the tests again without `vagrant-cachier`, and uploaded the results to a separate sheet so you can compare:

https://docs.google.com/spreadsheets/d/16H6TeKCOZRwzsd5bZJM2IHVqN9fU6GZhUrDiu_SK2zU/edit?usp=sharing

It performed one _fewer_ run, and battery runtime was 5.6 hours instead of 4.9. Interesting result, but I don't know if I can keep sacrificing my entire night and part of a morning (draining the battery resets the PMU, which resets the clock, which causes _all kinds of crazy_ with Apps that depend on the correct time) for these tests on one of my main laptops.
